DROP TABLE IF EXISTS movies;
CREATE TABLE movies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    year INTEGER NOT NULL,
    director TEXT NOT NULL,
    genres TEXT NOT NULL,
    original_language TEXT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);